### ISSUE TITLE
User Auth Issue (Recovered)

### ISSUE THREAD

**Issue by natedonato** [natedonato/instagraff#2]
*  Backend: DB, model, controller, views
*   Users can sign up, sign in, log out
*   Users can use a demo login to try the site
*   Styling (typing in demo user!)
*   Smooth, bug-free navigation
*   WE'RE LIVE ON HEROKU!

Hey nate, looks good! Here's some feedback:
Styling
When logged in
*   There's should be a navbar that is style
Auth forms
*   The inputs should have a little more height
*   I think the font choice for "Instagraff" could be a bit cleaner; I recommend something like this: https://fonts.google.com/specimen/Lobster
*   I saw a weird bug when I signedup and logged out, the "OR" text was in a weird spot, but I can't replicate this (keep your 👀 out)
*   cursor: pointer for your buttons
*   Make sure to unstyle the default behavior of this button (if you enter invalid parameters when signing up, and click the button, the button will have a gray border around it) 
￼
Bugs
*   Make sure to clear the errors between your forms. Right now I can go to login, click Login without any information, the error pops up, can click on sign up, and the errors are still there
Recommendations
*   Your auto typing demo should be a bit faster
*   Eventually, you should have a 404 page if a user navigates to a strange route: https://www.instagram.com/accounts/emailsignup/kljsdf

**Comment by evhumphrey** [comment]
- [ ] Make sure to style your logout button when you work on your user profile
